INSERT IGNORE INTO community_quotes (id, text, speaker, cover_path, sort_order, status, is_pinned) VALUES
  ('q-01', '这次真的不一样。', '匿名坑底人', 'assets/column/rival-lover/overview/01-kqpjbbks9obs.webp', 10, 'published', 0),
  ('q-02', '两眼一睁就是磕。', '匿名坑底人', NULL, 20, 'published', 0),
  ('q-03', '正主虚情热演，粉丝假意上头。', '匿名坑底人', 'assets/column/us/overview/01-jxntbv0oxoli.webp', 30, 'published', 0),
  ('q-04', '卖得专业就打赏，惹怒粉丝就换推。', '匿名坑底人', NULL, 40, 'published', 0),
  ('q-05', '只是售后，入坑三月都懂。', '匿名坑底人', NULL, 50, 'published', 0),
  ('q-06', '可以嗑，但不要嗑得那么执着。', '匿名坑底人', 'assets/column/designing-love/overview/01-ft0abcnezobo.webp', 60, 'published', 0),
  ('q-07', '每对 CP 在自己 CP 粉眼中都是真情侣。', '匿名坑底人', NULL, 70, 'published', 0),
  ('q-08', '在别家 CP 粉眼里都一眼假。', '匿名坑底人', 'assets/column/poisonous-love/overview/01-uksdb8nmjojx.webp', 80, 'published', 0),
  ('q-09', '路过的狗都得说一句好配。', '匿名坑底人', NULL, 90, 'published', 0),
  ('q-10', '谁家 CP 这么好磕？哦，原来是我家的。', '匿名坑底人', NULL, 100, 'published', 0),
  ('q-11', '般配，已经说累了。', '匿名坑底人', 'assets/column/my-secret-words/overview/01-suakby2xcohn.webp', 110, 'published', 0),
  ('q-12', '剧外也是一种浪漫。', '匿名坑底人', NULL, 120, 'published', 0),
  ('q-13', '我不入蛊谁入蛊？', '匿名坑底人', NULL, 130, 'published', 0),
  ('q-14', '滞后磕 CP 就是爽。', '匿名坑底人', 'assets/column/affair/overview/01-biwwbh7aeo6p.webp', 140, 'published', 0),
  ('q-15', '早期的糖也是糖。', '匿名坑底人', NULL, 150, 'published', 0),
  ('q-16', '只是同事？只是姐妹？谈了两年了？', '匿名坑底人', NULL, 160, 'published', 0),
  ('q-17', '谁嗑谁上头。', '匿名坑底人', NULL, 170, 'published', 0),
  ('q-18', '现实比剧本会写。', '匿名坑底人', NULL, 180, 'published', 0),
  ('q-pinned-host-note', '这里可以投稿，也可以在别人的卡片下接着聊。', '范米花儿 × Conceal', NULL, -1000, 'published', 1);
