export const cpCopy = {
  zh: {
    birthYearPending: '出生年份尚未核实',
    height: '身高', notVerified: '尚未核实', weibo: '微博', community: 'CP 超话', communityNote: '粉丝社区 · 非官方账号', searchCommunity: '搜索 CP 超话', communityPending: '尚未核实直达地址',
    profileNote: '个人资料综合艺人、经纪公司、公开媒体及 GL Spotlight 等资料目录；账号索引仅用于核对本人入口，不代表平台认证。未核实不等于未开通。微博和超话可能需要登录。',
    referenceKinds: { agency: '经纪公司', artist: '艺人公开页面', media: '公开媒体', catalogue: '资料目录', 'fan-index': '粉丝整理索引', organizer: '活动主办方' },
    switchCp: '切换 CP', allCps: '全部 CP', closeDirectory: '关闭 CP 目录',
    all: '全部', collapse: '收起', expandAll: '展开全部 CP', collapseAll: '收起全部 CP', clearSearch: '清除搜索', pairNameSource: 'CP 名称出处',
    search: '搜索 CP / 演员 / 剧名', noResults: '没有找到匹配的 CP，试试其他名字。', pairNote: '按已收录的荧幕合作整理，包括历史搭档；不代表当前经纪绑定或私人关系。未核实的账号与个人资料暂不展示。',
    birthday: '生日', zodiac: '星座', zodiacNote: '星座按公历生日与常用西方十二星座日期区间归类，仅作趣味资料，不用于性格判断。', previewImage: '官方预告封面', openPreview: '观看官方预告', profile: '个人资料',
    upcoming: '已官宣 · 档期待定', announcedProject: '已官宣项目 · 后续进展待确认', sources: '资料与来源', pendingNote: '尚未核实到明确播出日期，暂不列入日历。',
    calendar: '查看播出日历', cpCalendar: '她们的播出日历', archive: '考古档案', related: '相关 CP', allSeries: '查看全部剧集', scope: '当前查看',
    title: '百家饭', note: '每一种喜欢，都值得被认真记录。', select: '选择 CP',
    works: '她们的作品', viewWorks: '查看共同作品', viewWork: '查看作品详情',
    pair: '双人主线', ensemble: '群像作品', events: '公开活动', shops: '周边与品牌',
    announcement: '官方公告', recap: '活动回顾 · 已结束', officialShop: '官方周边', memberLink: '个人主页收录的品牌',
    openEvent: '查看官方公告', openRecap: '查看活动回顾', openShop: '前往官方商店', openBrand: '前往品牌网站',
    source: '资料来源', checked: '核对于', sourceNote: '收录已核实的公开资料。活动安排与商品信息，以官方页面为准。',
    notFound: '暂未收录这对 CP', back: '返回百家饭', name: 'CP 档案',
  },
  en: {
    birthYearPending: 'Birth year not verified',
    height: 'Height', notVerified: 'Not verified', weibo: 'Weibo', community: 'CP Super Topic', communityNote: 'Fan community · Not an official account', searchCommunity: 'Search CP Super Topics', communityPending: 'Direct community link not verified',
    profileNote: 'Profiles draw on artists, agencies, public media and catalogues including GL Spotlight. Account indexes help identify personal profiles, not platform verification. Unverified does not mean an account does not exist. Weibo and Super Topics may require login.',
    referenceKinds: { agency: 'Agency', artist: 'Artist page', media: 'Public media', catalogue: 'Profile catalogue', 'fan-index': 'Fan-curated index', organizer: 'Event organizer' },
    switchCp: 'Switch CP', allCps: 'All CPs', closeDirectory: 'Close CP directory',
    all: 'All', collapse: 'Less', expandAll: 'Show all CPs', collapseAll: 'Collapse all CPs', clearSearch: 'Clear search', pairNameSource: 'Pairing name reference',
    search: 'Search CP / actor / series', noResults: 'No matching CP. Try another name.', pairNote: 'Organized by screen collaborations, including past pairings. This does not imply a current agency partnership or private relationship. Unverified accounts and personal details are omitted.',
    birthday: 'Birthday', zodiac: 'Zodiac', zodiacNote: 'Signs use Gregorian birthdays and common Western zodiac date ranges, for fun rather than personality claims.', previewImage: 'Official trailer cover', openPreview: 'Watch official trailer', profile: 'Profile',
    upcoming: 'Announced · Date TBA', announcedProject: 'Announced project · Further updates unconfirmed', sources: 'Information & sources', pendingNote: 'No confirmed airing date in our records; not included in the calendar.',
    calendar: 'Airing calendar', cpCalendar: 'Their airing calendar', archive: 'Series archive', related: 'Related CP', allSeries: 'Show all series', scope: 'Showing',
    title: 'CP Archive', note: 'Every story we love deserves a place.', select: 'Choose a CP',
    works: 'Their work', viewWorks: 'Explore their work', viewWork: 'View series', pair: 'Paired leads', ensemble: 'Ensemble',
    events: 'Public events', shops: 'Merch & brands', announcement: 'Official announcement', recap: 'Event recap · Ended',
    officialShop: 'Official merchandise', memberLink: 'Brand linked from personal profile', openEvent: 'View announcement',
    openRecap: 'Read the recap', openShop: 'Visit official shop', openBrand: 'Visit brand', source: 'Source', checked: 'Checked',
    sourceNote: 'A collection of verified public information. Refer to official pages for event and product updates.',
    notFound: 'This CP is not in the archive yet', back: 'Back to CP Archive', name: 'CP Archive',
  },
  th: {
    birthYearPending: 'ยังไม่ยืนยันปีเกิด',
    height: 'ส่วนสูง', notVerified: 'ยังไม่ยืนยัน', weibo: 'Weibo', community: 'ซูเปอร์ท็อปปิกของคู่', communityNote: 'ชุมชนแฟนคลับ · ไม่ใช่บัญชีทางการ', searchCommunity: 'ค้นหาซูเปอร์ท็อปปิก', communityPending: 'ยังไม่ยืนยันลิงก์ตรงของชุมชน',
    profileNote: 'ข้อมูลมาจากนักแสดง ต้นสังกัด สื่อสาธารณะ และฐานข้อมูล เช่น GL Spotlight รายการบัญชีใช้ตรวจสอบช่องทางส่วนตัว ไม่ใช่การรับรองจากแพลตฟอร์ม ยังไม่ยืนยันไม่ได้แปลว่าไม่มีบัญชี Weibo และซูเปอร์ท็อปปิกอาจต้องเข้าสู่ระบบ',
    referenceKinds: { agency: 'ต้นสังกัด', artist: 'หน้านักแสดง', media: 'สื่อสาธารณะ', catalogue: 'ฐานข้อมูลประวัติ', 'fan-index': 'ข้อมูลที่แฟนคลับรวบรวม', organizer: 'ผู้จัดกิจกรรม' },
    switchCp: 'เปลี่ยนคู่', allCps: 'คู่ทั้งหมด', closeDirectory: 'ปิดรายชื่อคู่',
    all: 'ทั้งหมด', collapse: 'ย่อ', expandAll: 'แสดงทุกคู่', collapseAll: 'ย่อรายชื่อคู่', clearSearch: 'ล้างการค้นหา', pairNameSource: 'ที่มาของชื่อคู่',
    search: 'ค้นหาคู่ / นักแสดง / ซีรีส์', noResults: 'ไม่พบคู่ที่ตรงกัน ลองค้นหาด้วยชื่ออื่น', pairNote: 'จัดตามผลงานร่วมกันบนจอ รวมถึงคู่ในอดีต ไม่ได้หมายถึงสัญญาคู่ในปัจจุบันหรือความสัมพันธ์ส่วนตัว ข้อมูลและบัญชีที่ยังไม่ยืนยันจะไม่แสดง',
    birthday: 'วันเกิด', zodiac: 'ราศี', zodiacNote: 'ราศีอ้างอิงวันเกิดตามปฏิทินสากลและช่วงวันที่แบบตะวันตก เป็นข้อมูลเพื่อความสนุก ไม่ใช้ตัดสินบุคลิก', previewImage: 'ภาพปกตัวอย่างทางการ', openPreview: 'ดูตัวอย่างทางการ', profile: 'ประวัติ',
    upcoming: 'ประกาศแล้ว · รอกำหนดฉาย', announcedProject: 'ประกาศโปรเจกต์แล้ว · รอยืนยันความคืบหน้า', sources: 'ข้อมูลและแหล่งอ้างอิง', pendingNote: 'ยังไม่มีวันออกอากาศที่ยืนยันในข้อมูล จึงยังไม่แสดงในปฏิทิน',
    calendar: 'ปฏิทินออกอากาศ', cpCalendar: 'ปฏิทินของทั้งคู่', archive: 'คลังซีรีส์', related: 'คู่ที่เกี่ยวข้อง', allSeries: 'ดูซีรีส์ทั้งหมด', scope: 'กำลังแสดง',
    title: 'รวมทุกคู่', note: 'ทุกเรื่องราวที่ชอบ ควรค่าแก่การบันทึก', select: 'เลือกคู่',
    works: 'ผลงานของทั้งคู่', viewWorks: 'ดูผลงานร่วมกัน', viewWork: 'ดูรายละเอียดซีรีส์', pair: 'คู่ตัวละครหลัก', ensemble: 'นักแสดงนำหลายคู่',
    events: 'กิจกรรมสาธารณะ', shops: 'สินค้าและแบรนด์', announcement: 'ประกาศทางการ', recap: 'ย้อนชมกิจกรรม · จบแล้ว',
    officialShop: 'สินค้าทางการ', memberLink: 'แบรนด์ที่ลิงก์จากโปรไฟล์ส่วนตัว', openEvent: 'ดูประกาศทางการ', openRecap: 'ย้อนชมกิจกรรม',
    openShop: 'ไปยังร้านค้าทางการ', openBrand: 'ไปยังเว็บไซต์แบรนด์', source: 'แหล่งข้อมูล', checked: 'ตรวจสอบเมื่อ',
    sourceNote: 'รวบรวมข้อมูลสาธารณะที่ตรวจสอบแล้ว โปรดตรวจสอบกิจกรรมและสินค้าล่าสุดจากช่องทางทางการ',
    notFound: 'ยังไม่มีคู่นี้ในคลัง', back: 'กลับไปหน้ารวมทุกคู่', name: 'คลังข้อมูลคู่',
  },
};
